// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/backup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backup.post').default>>>>
    }
    '/api/devices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices.get').default>>>>
    }
    '/api/restore': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/restore.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}