// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/26/2026, 11:42:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/ricardosaldanha/learn/ha-lightcontroller-addon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/plugins/**/*.{js,ts,mjs}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/composables/**/*.{js,ts,mjs}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/utils/**/*.{js,ts,mjs}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ricardosaldanha/learn/ha-lightcontroller-addon/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;